# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea446a2048486517c4a50682b6535ea5d24a98b6ff007bc8603652c894fa6c4d113a73bdddefb1d6866012a6eb788b50a515fc6949cde8987b64b95f170929a0

test:
  secret_key_base: f140ead7831992760c40f62b5eeef935f1a77c7c525a994033ce1baf1fbce3ec32a61167f52f0d0e3b3441fa05e10120984cabaddfb480bcd8efe4d06adfa147

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
